#version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: server_postgres0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: companhia_aerea
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      rede_docker:
        ipv4_address: 172.12.0.15
