apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- postgres-deployment.yaml
- postgres-service.yaml
- rabbitmq-deployment.yaml
- rabbitmq-service.yaml
- app-configmap.yaml
- app-deployment.yaml
- app-service.yaml
